# Generated by Django 3.1 on 2020-09-11 08:31

import boardapp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hitcount.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, null=True, verbose_name='과목')),
                ('professor', models.CharField(max_length=10, null=True, verbose_name='교수')),
                ('item', models.CharField(choices=[('중간', '중간'), ('기말', '기말'), ('과제', '과제')], max_length=10, null=True, verbose_name='항목')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='글 제목')),
                ('year', models.IntegerField()),
                ('hits', models.IntegerField(default=0)),
                ('upload_files', models.FileField(blank=True, null=True, upload_to=boardapp.models.get_file_path)),
                ('filename', models.CharField(max_length=64, null=True, verbose_name='파일 이름')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
        migrations.CreateModel(
            name='DataroomBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(blank=True, max_length=50)),
                ('item', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DjangoBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('nick_name', models.CharField(blank=True, max_length=50)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('memo', models.CharField(blank=True, max_length=200)),
                ('hits', models.IntegerField(default=0)),
            ],
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
        migrations.CreateModel(
            name='SubBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subname', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
