# Generated by Django 3.1.1 on 2020-09-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataroomBoard',
        ),
        migrations.DeleteModel(
            name='DjangoBoard',
        ),
        migrations.DeleteModel(
            name='SubBoard',
        ),
    ]
