# Generated by Django 2.2.6 on 2020-08-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_auto_20200818_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djangoboard',
            name='content',
        ),
        migrations.RemoveField(
            model_name='djangoboard',
            name='created_date',
        ),
        migrations.AddField(
            model_name='djangoboard',
            name='item',
            field=models.CharField(max_length=10, null=True, verbose_name='항목'),
        ),
        migrations.AddField(
            model_name='djangoboard',
            name='professor',
            field=models.CharField(max_length=10, null=True, verbose_name='교수'),
        ),
        migrations.AddField(
            model_name='djangoboard',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='글 제목'),
        ),
        migrations.AddField(
            model_name='djangoboard',
            name='year',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='djangoboard',
            name='subject',
            field=models.CharField(max_length=50, null=True, verbose_name='과목'),
        ),
    ]
