# Generated by Django 3.1 on 2020-08-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0007_dataroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataroomBoard',
        ),
        migrations.AddField(
            model_name='dataroom',
            name='pro',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
