# Generated by Django 3.1 on 2020-08-30 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0008_auto_20200830_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataroom',
            old_name='name',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='dataroom',
            old_name='pro',
            new_name='professor',
        ),
        migrations.RenameField(
            model_name='dataroom',
            old_name='sub',
            new_name='subject',
        ),
    ]
